#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

LOG_DIR="$ROOT_DIR/reports/live_monitor/live_trade_ready"
mkdir -p "$LOG_DIR"

export PYTHONPATH="$ROOT_DIR${PYTHONPATH:+:$PYTHONPATH}"
export ROI_SNIPS_ALLOW_LIVE_ORDER_SUBMISSION=true
export ROI_SNIPS_ALLOW_PAPER_ORDER_SUBMISSION=false
export ROI_SNIPS_REQUIRE_DEEP_MINI_FOR_LIVE_RESEARCH="${ROI_SNIPS_REQUIRE_DEEP_MINI_FOR_LIVE_RESEARCH:-true}"
export ROI_SNIPS_REQUIRE_GROK_FOR_LIVE_RESEARCH="${ROI_SNIPS_REQUIRE_GROK_FOR_LIVE_RESEARCH:-false}"
export ROI_SNIPS_RUN_CONTINUATION_MONITOR=true
export ROI_SNIPS_OPENING_STREAM_MAX_SECONDS="${ROI_SNIPS_OPENING_STREAM_MAX_SECONDS:-900}"
export ROI_SNIPS_SHADOW_SKIP_BROKER_PREFLIGHT=false
export ROI_SNIPS_SKIP_BROKER_STATE_FOR_SHADOW=false

exec scripts/supervise_opening_bell_live_monitor.sh "$@"
