from __future__ import annotations

EARLY_CATALYST_DISCOVERY = "EARLY_CATALYST_DISCOVERY"
PREMARKET_BUILDING = "PREMARKET_BUILDING"
OPENING_DRIVE_ACTIVE = "OPENING_DRIVE_ACTIVE"
EXTENDED_CHASE = "EXTENDED_CHASE"
SECOND_LEG_WATCH = "SECOND_LEG_WATCH"
SECOND_LEG_RESET = "SECOND_LEG_RESET"
OPENING_CONTINUATION_ACTIVE = "OPENING_CONTINUATION_ACTIVE"
SECOND_LEG_CONTINUATION_ACTIVE = "SECOND_LEG_CONTINUATION_ACTIVE"
EXHAUSTED_OR_DISTRIBUTING = "EXHAUSTED_OR_DISTRIBUTING"
STALE_PRIOR_WINNER = "STALE_PRIOR_WINNER"
NO_TRADE_EXTENDED = "NO_TRADE_EXTENDED"

ALL_LIFECYCLE_STATES = {
    EARLY_CATALYST_DISCOVERY,
    PREMARKET_BUILDING,
    OPENING_DRIVE_ACTIVE,
    EXTENDED_CHASE,
    SECOND_LEG_WATCH,
    SECOND_LEG_RESET,
    OPENING_CONTINUATION_ACTIVE,
    SECOND_LEG_CONTINUATION_ACTIVE,
    EXHAUSTED_OR_DISTRIBUTING,
    STALE_PRIOR_WINNER,
    NO_TRADE_EXTENDED,
}

